### =========================================================================


### PENGUJIAN API: FORMAT FORM-URLENCODED


### =========================================================================
@baseUrl = http://smkn1tgb.local/api/v1
@form = application/x-www-form-urlencoded
@json = application/json
@foto_1x1 = iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=


### -------------------------------------------------------------------------


### 1. LOGIN SISWA (Mendapatkan Token & Mengikat Device ID)


### -------------------------------------------------------------------------
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{form}}
Accept: {{json}}

nis=20260001&device_id=ANDROID-ID-88X99Y00Z


### -------------------------------------------------------------------------


### SIMPAN TOKEN OTOMATIS (Jangan dihapus)


### -------------------------------------------------------------------------
@token = {{login.response.body.data.token}}


### =========================================================================


### -------------------------------------------------------------------------


### 2. ABSEN MASUK (Berhasil / Tepat Waktu)


### -------------------------------------------------------------------------
POST {{baseUrl}}/absen/masuk
Content-Type: {{form}}
Accept: {{json}}
Authorization: Bearer {{token}}

lat=-6.914744&long=107.609810&is_mock=false&foto={{foto_1x1}}


### =========================================================================


### -------------------------------------------------------------------------


### 3. ABSEN MASUK (Gagal - Di Luar Geofence)


### -------------------------------------------------------------------------
POST {{baseUrl}}/absen/masuk
Content-Type: {{form}}
Accept: {{json}}
Authorization: Bearer {{token}}

lat=-6.920000&long=107.610000&is_mock=false&foto={{foto_1x1}}


### =========================================================================


### -------------------------------------------------------------------------


### 4. ABSEN MASUK (Terdeteksi Fake GPS)


### -------------------------------------------------------------------------
POST {{baseUrl}}/absen/masuk
Content-Type: {{form}}
Accept: {{json}}
Authorization: Bearer {{token}}

lat=-6.914744&long=107.609810&is_mock=true&foto={{foto_1x1}}


### =========================================================================


### -------------------------------------------------------------------------


### 5. ABSEN PULANG


### -------------------------------------------------------------------------
POST {{baseUrl}}/absen/pulang
Content-Type: {{form}}
Accept: {{json}}
Authorization: Bearer {{token}}

lat=-6.914744&long=107.609810&is_mock=false&foto={{foto_1x1}}


### =========================================================================


### -------------------------------------------------------------------------


### 6. RIWAYAT ABSENSI


### -------------------------------------------------------------------------
GET {{baseUrl}}/absen/riwayat
Accept: {{json}}
Authorization: Bearer {{token}}


### =========================================================================


### -------------------------------------------------------------------------


### 7. TRACKING LOKASI BACKGROUND


### -------------------------------------------------------------------------
POST {{baseUrl}}/tracking/update_lokasi
Content-Type: {{form}}
Accept: {{json}}
Authorization: Bearer {{token}}

lat=-6.914744&long=107.609810